version: "3"

services:
  postgres:
    image: postgres:12
    restart: always
    environment:
      - POSTGRES_DB
      - POSTGRES_USER
      - POSTGRES_PASSWORD
    ports:
      - 5432:5432
    volumes:
      - /Users/thalida/Repos/unpack.link/postgres/data:/var/lib/postgresql/data

  redis:
    image: redis:alpine
    ports:
      - 6379:6379

  rabbitmq:
    image: rabbitmq:3-management-alpine
    ports:
      - 15672:15672
      - 5672:5672

  elk:
    image: sebp/elk:latest
    restart: always
    ports:
      - 5959:5959
      - 5601:5601
      - 9200:9200
      - 5044:5044
    volumes:
      - /Users/thalida/Repos/unpack.link/elk/elasticsearch:/var/lib/elasticsearch
      - /Users/thalida/Repos/unpack.link/elk/logstash:/etc/logstash/conf.d
      - /Users/thalida/Repos/unpack.link/elk/archive:/archive

  unpack:
    build: ./unpack
    image: unpack
    depends_on:
      - postgres
      - rabbitmq
      - redis
      - elk
    command: 'api'
    ports:
      - 5000:5000
    environment:
      - UNPACK_HOST
      - UNPACK_DEV_ENV
      - UNPACK_DEV_PROFILER
      - UNPACK_DB_NAME
      - UNPACK_DB_USER
      - UNPACK_DB_PASSWORD
      - PYTHONUNBUFFERED=false
    volumes:
      - /Users/thalida/Repos/unpack.link/unpack:/unpack
      - /var/run/docker.sock:/var/run/docker.sock

  app:
    build: ./app
    image: app
    ports:
      - 8080:80
