version: "3"

services:
  redis:
    image: redis:alpine
    ports:
      - 6379:6379

  rabbitmq:
    image: rabbitmq:3-management-alpine
    ports:
      - 15672:15672
      - 5672:5672

  frontend_app:
    build: ./app
    image: frontend_app
    ports:
      - 8080:80

  api:
    build: .
    image: unpack_container
    depends_on:
      - rabbitmq
      - redis
    command: 'api'
    ports:
      - 5000:5000
    environment:
      - UNPACK_HOST
      - UNPACK_DEV_ENV
      - UNPACK_DEV_PROFILER
      - UNPACK_DB_NAME
      - UNPACK_DB_USER
      - UNPACK_DB_PASSWORD
      - PYTHONUNBUFFERED=false
    volumes:
      - /Users/thalida/Repos/unpack.link/unpack:/unpack
      - /Users/thalida/Repos/unpack.link/controller.py:/controller.py
      - /var/run/docker.sock:/var/run/docker.sock
      - /tmp/unpack_api_logs.log:/tmp/unpack_logs.log
